### ISSUE TITLE
v1.5.17 has been released 

### ISSUE THREAD

**Issue by phobson** [conda-forge/shapely-feedstock#11]
https://pypi.python.org/pypi/Shapely

Fixes a memory leak. 

Happy to submit a PR. Quick question: do I generate the SHA256 myself or is there a clever way to look that up?

**Comment by ocefpaf** [comment]
> Happy to submit a PR.

Thanks! Hopefully refreshing the patches won't be necessary. If so ping me and I can do that for you.

> Happy to submit a PR. Quick question: do I generate the SHA256 myself or is there a clever way to look that up?

No clever way... Sorry. See https://github.com/conda-forge/staged-recipes#2-how-do-i-populate-the-hash-field
