### ISSUE TITLE
shapely=2.0.0 linux64 from conda-forge pkg_resources.UnknownExtra: shapely 2.0.0 has no such extra feature 'vectorized'

### ISSUE THREAD

**Issue by valeriupredoi** [conda-forge/shapely-feedstock#121]
The new shapely=2.0.0 for linux64, namely:

```
shapely                           2.0.0  py310h8b84c32_0              conda-forge/linux-64
```

makes our entry point call to our tool to fail from within pkg_resources, see [example failed test](https://github.com/ESMValGroup/ESMValTool/actions/runs/3692370204/jobs/6251200361); I saw there are lots of changes for this major release, perhaps `vectorized` was ommitted from the package at upload stage? Cheers, guys, and happy holidays :christmas_tree:

**Comment by valeriupredoi** [comment]
too true, @ocefpaf :+1: We need to change our imports (and functionality too) since there is indeed no more `vectorized` module. Cheers for this, Filipe! :beer:

**Comment by jorisvandenbossche** [comment]
There actually still is a `shapely.vectorized` module (https://github.com/shapely/shapely/tree/main/shapely/vectorized) .. 
(it's mostly a small shim for back compat, to be deprecated/removed later)

**Comment by jorisvandenbossche** [comment]
(and I quickly checked, it is also correctly included in the conda package, so not sure where your error comes from)

**Comment by valeriupredoi** [comment]
@jorisvandenbossche cheers muchly for getting back, mate! You are completely right - your package is shipshape, and my apologies for barking at the wrong tree, in the meantime I have managed to find the cuplrit, it's a dependency of ours, maintained by us , it wasn't immediately obvious since that particular dependency works fine on its own, until a pip install of the package that uses it, at which point the deps table gets pulled from `setup.py, where, lo and behold we require `shapely[vectorized]` :grin: Here's the issue at hand https://github.com/ESMValGroup/ESMValCore/issues/1874 Cheers for your support, guys, and happy holidays :christmas_tree:

**Comment by jorisvandenbossche** [comment]
Ah, but that is actually a good point that one could do `pip install shapely[vectorized]` before, and we removed that ability. We should at least document that (and we could also consider adding it back as dummy extra, just to not error on it)

**Comment by valeriupredoi** [comment]
I guess you could indeed, but if `shapely` is now fully vectorized, wouldn't that be a bit misleading? Maybe, as you mention, document it, add the functionality so that a package doesn't break the installation of another package that uses that one, and add a deprecation warning that it'll be completely removed in one or two minor releases? Cheers :beer:
