### ISSUE TITLE
Installing Shapely from conda-forge via Anaconda causes Anaconda environment to fail

### ISSUE THREAD

**Issue by MCBama** [conda-forge/shapely-feedstock#22]
Perhaps I'm doing something wrong but when I install shapely via the conda-forge within the Anaconda prompt the Anaconda Scripts folder gets modified and the activate.bat and deactivate.bat files get removed meaning I am no longer able to access Anaconda, conda, or anything that I've setup using it as the environment can no longer be activated.

OS: Windows 10
Anaconda Version: [Anaconda3 4.4.0 64 bit with Python 3.6](https://www.continuum.io/downloads)

After installing Anaconda I open the Anaconda Prompt and run the setup steps for shapely:
```
conda config --add channels conda-forge
conda install shapely
```
After the install finishes I can access shapely within the python console so everything seems to be setup. But when I shut down the Prompt and attempt to restart it later I get the error:
```
'C:\Users\<username>\AppData\Local\Continuum\Anaconda3\Scripts\activate.bat' is not recognized as an internal or external command, operable program or batch file.
```

Going into the scripts folder I noticed that the `activate`, `activate.bat`, `deactivate`, and `deactivate.bat` files had all been removed. So I uninstalled and reinstalled Anaconda, copied the activate/deactivate scripts into another folder, re-ran the shapely install steps, and then copied the activate/deactivate scripts back to where they belonged and my Anaconda Prompt worked fine and had access to Shapely.

Am I installing something incorrectly or perhaps going away from the normal workflow for installing conda-forge packages?

**Comment by ocefpaf** [comment]
I am not a Windows user to test that but I don't really think the issue is with `conda-forge` packages.
Did you report this to continuum? Maybe @msarahan can help here.

**Comment by MCBama** [comment]
I would have thought the same if I could find another package that did it but so far the other packages I've installed have left the scripts where they belong.

**Comment by MCBama** [comment]
After some more testing it appears that even simply updating conda removes the scripts so perhaps it's not shapely specific after all. Closing until I know more.
