### ISSUE TITLE
1.6.0?

### ISSUE THREAD

**Issue by apiszcz** [conda-forge/shapely-feedstock#25]
What is the expected drop for 1.6.0? Thanks.

There appear to be a number of improvements
https://github.com/Toblerity/Shapely/blob/master/CHANGES.txt

**Comment by ocefpaf** [comment]
I had a PR ready and I was being lazy to refresh the patch. But it seems that we no longer need the patch! Fingers crossed: https://github.com/conda-forge/shapely-feedstock/pull/26
