### ISSUE TITLE
shapely version 1.6.2 causes jupyter kernel to fail

### ISSUE THREAD

**Issue by fedhere** [conda-forge/shapely-feedstock#32]
Installation of shapely version 1.6.2 reintroduces issues that kill jupyter kernel. I think its the same issue that causes this [Toblerity/Shapely/issues/416](https://github.com/Toblerity/Shapely/issues/416) which was resolved by conda-forge install (possibly on a new conda environment). For me on a new conda environment either python2 or python3 the conda-forge installation that defaults to version 1.6.2 causes most shapely calls to kill kernel:

````
from shapely import geometry

coords = [-73.99, 40.70]

geometry.Point(coords) #call to Point works

geometry.Polygon([(0, 0), (1, 1), (1, 0)]) #call to Polygon kills kernel
````

set up that works:

> Darwin
> x86_64
> python 3.6.3 | packaged by conda-forge | (default, Nov  4 2017, 10:13:32) 
> [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
> shapely 1.6.2

set up that works:

> Darwin
> x86_64
> python 3.6.3 | packaged by conda-forge | (default, Nov  4 2017, 10:13:32) 
> [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
> shapely 1.5.17.post1

(note that installing geopandas=0.3 upgrades shapely to v1.6.2 automatically)

**Comment by ocefpaf** [comment]
Can you provide the steps you used to install it in your env? Also, do you have a system installation of GEOS?

**Comment by fedhere** [comment]
the succesfull shapely1.15 installation is as follows
conda create --name py36 python=3.6
```
source activate py36
conda install -c conda-forge shapely=1.5.17
python -m ipykernel install --user
conda install -c conda-forge jupyter notebook
```

what I would normally have done is to install geopandas directly which installs shapely 1.6 and would give the kernel crush (also simply installing shapely 1.6 gives the error)

```
GEOS is installed when shapely 1.5 is installed
    geos:         3.5.1-1               conda-forge
    intel-openmp: 2018.0.0-h8158457_8              
    libgfortran:  3.0.1-h93005f0_2                 
    mkl:          2018.0.1-hfbd8650_4              
    numpy:        1.13.3-py36h2cdce51_0            
    shapely:      1.5.17-py36_4         conda-forge
```

shapely 1.6 updates geos

```
The following NEW packages will be INSTALLED:

    shapely: 1.6.2-py36_1 conda-forge

The following packages will be UPDATED:

    geos:    3.5.1-1      conda-forge --> 3.6.2-1 conda-forge
```

said that I am not sure how to find out if shapely actually taps a system GEOS install (I think I read something along those lines in someone's post)

**Comment by ocefpaf** [comment]
> said that I am not sure how to find out if shapely actually taps a system GEOS install (I think I read something along those lines in someone's post)

My guess is that a system `geos` might be found and it is causing the library hell there. Unfortunately I cannot reproduce the error to investigate. Everything works OK on my Linux machine even with a system `geos` :-/

I will double check conda-forge's patches though b/c I thought we worked around avoid that already.

**Comment by ocefpaf** [comment]
Closing this as stale. Please let me know if you still experience this with the latest version.

**Comment by j-la-haye** [comment]
Hi, I am trying to run the same code/installation process with shapely version 1.5.17 and 1.6 but my kernal is still crashing. I have set the conda config file to default to the conda-forge channel as noted here: [https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels]. Any other thing that I may have overlooked?

**Comment by j-la-haye** [comment]
Update, I can get this to work in jupyter notebooks, but not in jupyter lab.

**Comment by ocefpaf** [comment]
> Update, I can get this to work in jupyter notebooks, but not in jupyter lab.

I don't think there is anything that is `jupyter`/`lab` specific that can explain that failure. Maybe you are calling different `Python` installations/kernels there, no?
