### ISSUE TITLE
Consider pulling this into defaults

### ISSUE THREAD

**Issue by pelson** [conda-forge/shapely-feedstock#5]
It has long been the case that the shapely shipped by `defaults` is broken. (https://github.com/Toblerity/Shapely/issues/177, https://github.com/SciTools/cartopy/issues/753, https://github.com/SciTools/cartopy/issues/738, https://github.com/Toblerity/Shapely/issues/177, https://github.com/SciTools/cartopy/issues/651, https://github.com/SciTools/cartopy/issues/612).

Is there any chance this recipe can be pulled into `defaults` @msarahan?

(@ocefpaf - please add any comments if I'm mis-remembering)

**Comment by ocefpaf** [comment]
It has been a while that I don't try `shapely` from `defauts`, but I believe if the problem still exists. (Specially if people have more than one version of geos installed.)

**Comment by msarahan** [comment]
Sure.  Good to see the Continuum question label!

I'm going to look briefly into what it will take to have fully rendered meta.yaml files stored with packages.  I think that is what is necessary to have easy integration of jinja2 recipes with the internal build system and repository creation.  Any thoughts on storing an unrendered backup copy with the package?

**Comment by pelson** [comment]
Our jinja variables are pretty much exclusively simple and can be rendered with:

```
python -c "from jinja2 import FileSystemLoader, Environment; print(Environment(loader=FileSystemLoader('recipe')).get_template('meta.yaml').render())"
```

**Comment by msarahan** [comment]
That's easy!  Thanks!  Any thoughts on storing a backup?  Is that worth having?  I think it might be.

    meta.yaml.raw

or something else?

**Comment by pelson** [comment]
> or something else?

How about putting a link back to this feedstock along with the SHA?

**Comment by msarahan** [comment]
I'm not sure I could derive that from meta.yaml.  This is something that I imagine happening at build time, not some manual process that I'm doing.

That said - it sounds like a great idea, and we should add that to all the recipes on conda forge!  What would it take to have the CI update the SHA in meta.yaml on each accepted PR?

**Comment by pelson** [comment]
I meant the git commit SHA so that I can go back and get it, rather than the SHA of the file itself.

Depending on the process you had in mind, I could imagine something like:

```
from jinja2 import FileSystemLoader, Environment
import git


repo = git.Repo('.')
environment = Environment(loader=FileSystemLoader('recipe'))

print('# This recipe has been converted automatically from conda-forge ({}).'.format(repo.head.object.hexsha))
print('# Please raise any issues at https://github.com/conda-forge/shapely-feedstock.\n')
print(environment.get_template('meta.yaml').render())
```

**Comment by msarahan** [comment]
Yes, this is pretty much exactly what I had hoped for.  I'll see about adding the URL automatically based on git's repo info, and also generalize it so it's not just for conda-forge recipes, but templated recipes from any git repo.

**Comment by pelson** [comment]
@msarahan - I don't know if you are aware of it, but the script which keeps the [feedstocks submodule](https://github.com/conda-forge/feedstocks) up to date can be found at https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/update_feedstocks_submodules.py. 

That is making use of the conda-smithy feedstocks API (also available via a CLI) to work with the many repos model.

For instance, if I wanted to keep a directory containing all of the conda-forge feedstocks locally (I do so that I can grep them):

```
mkdir -p feedstocks && cd feedstocks
feedstocks clone
feedstocks apply-cloned -- git --no-pager diff
```

If you want to know more, just shout and I'd happily show you.

**Comment by ocefpaf** [comment]
I guess that this will happen eventually when we move to `conda-build 3` and the new pinning scheme. Closing this for now.
